//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalPopup.TfsOpretBugProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="dk.dsa.facit.guifacitconnector/", ConfigurationName="TfsOpretBugProxy.OpretBugItemSoap")]
    public interface OpretBugItemSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="dk.dsa.facit.guifacitconnector/AnmeldEnfejl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(LogableDto))]
        string AnmeldEnfejl(GlobalPopup.TfsOpretBugProxy.AnmeldFejlDto hentetData);
        
        [System.ServiceModel.OperationContractAttribute(Action="dk.dsa.facit.guifacitconnector/AnmeldEnfejl", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AnmeldEnfejlAsync(GlobalPopup.TfsOpretBugProxy.AnmeldFejlDto hentetData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dk.dsa.facit.guifacitconnector/")]
    public partial class AnmeldFejlDto : LogableDto {
        
        private string fileField;
        
        private byte[] dataField;
        
        private string currentUserFullNameField;
        
        private string cprNummerField;
        
        private string currentProcessNavnField;
        
        private string procesTrinField;
        
        private string beskrivelseField;
        
        private System.Guid procesInstansIdField;
        
        private string areaTypeField;
        
        private string iterationTypeField;
        
        private string titleField;
        
        private string rootCauseField;
        
        private string urgencyField;
        
        private string impactField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
                this.RaisePropertyChanged("File");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CurrentUserFullName {
            get {
                return this.currentUserFullNameField;
            }
            set {
                this.currentUserFullNameField = value;
                this.RaisePropertyChanged("CurrentUserFullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CprNummer {
            get {
                return this.cprNummerField;
            }
            set {
                this.cprNummerField = value;
                this.RaisePropertyChanged("CprNummer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CurrentProcessNavn {
            get {
                return this.currentProcessNavnField;
            }
            set {
                this.currentProcessNavnField = value;
                this.RaisePropertyChanged("CurrentProcessNavn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProcesTrin {
            get {
                return this.procesTrinField;
            }
            set {
                this.procesTrinField = value;
                this.RaisePropertyChanged("ProcesTrin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Beskrivelse {
            get {
                return this.beskrivelseField;
            }
            set {
                this.beskrivelseField = value;
                this.RaisePropertyChanged("Beskrivelse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Guid ProcesInstansId {
            get {
                return this.procesInstansIdField;
            }
            set {
                this.procesInstansIdField = value;
                this.RaisePropertyChanged("ProcesInstansId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AreaType {
            get {
                return this.areaTypeField;
            }
            set {
                this.areaTypeField = value;
                this.RaisePropertyChanged("AreaType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string IterationType {
            get {
                return this.iterationTypeField;
            }
            set {
                this.iterationTypeField = value;
                this.RaisePropertyChanged("IterationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RootCause {
            get {
                return this.rootCauseField;
            }
            set {
                this.rootCauseField = value;
                this.RaisePropertyChanged("RootCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("Urgency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Impact {
            get {
                return this.impactField;
            }
            set {
                this.impactField = value;
                this.RaisePropertyChanged("Impact");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AnmeldFejlDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dk.dsa.facit.guifacitconnector/")]
    public abstract partial class LogableDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OpretBugItemSoapChannel : GlobalPopup.TfsOpretBugProxy.OpretBugItemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OpretBugItemSoapClient : System.ServiceModel.ClientBase<GlobalPopup.TfsOpretBugProxy.OpretBugItemSoap>, GlobalPopup.TfsOpretBugProxy.OpretBugItemSoap {
        
        public OpretBugItemSoapClient() {
        }
        
        public OpretBugItemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OpretBugItemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpretBugItemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OpretBugItemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AnmeldEnfejl(GlobalPopup.TfsOpretBugProxy.AnmeldFejlDto hentetData) {
            return base.Channel.AnmeldEnfejl(hentetData);
        }
        
        public System.Threading.Tasks.Task<string> AnmeldEnfejlAsync(GlobalPopup.TfsOpretBugProxy.AnmeldFejlDto hentetData) {
            return base.Channel.AnmeldEnfejlAsync(hentetData);
        }
    }
}
